name: CI Homolog

on:
  pull_request:
    types: [closed]
    branches:
      - homolog

jobs:
  run-tests:
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'homolog'
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.9'

      - name: Build and Run Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: |
          mvn clean install
          mvn test

  create-pr-to-main:
    runs-on: ubuntu-latest
    needs: run-tests
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "anndrezoide"
          git config --global user.email "dhegomeez@gmail.com"

      - name: Create Pull Request to Main
        id: create-pr-main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: homolog
          title: "PR: Merge homolog into main"
          body: "Este PR foi criado automaticamente para merge de homolog em main."
          draft: false
