name: CI/CD Pipeline with Tests and PR Automation

on:
  push:
    branches:
      - develop  # A pipeline será acionada apenas com push na branch "develop"

permissions:
  contents: write
  pull-requests: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      # Passo 3: Configurar Maven 3.9.9
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.9'

      # Passo 4: Executar build e testes
      - name: Build and Run Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: postgres
        run: |
          mvn clean install
          mvn test

  create-pr-to-homolog:
    runs-on: ubuntu-latest
    needs: run-tests  # Só executa após os testes passarem
    if: success()  # Só executa se os testes passarem

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Git
      - name: Set up Git
        run: |
          git config --global user.name "anndrezoide"
          git config --global user.email "dhegomeez@gmail.com"

      # Passo 3: Criar Pull Request de develop para homolog
      - name: Create Pull Request to Homolog
        id: create-pr-homolog
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: homolog  # Branch de destino
          head: develop  # Branch de origem
          title: "PR: Merge develop into homolog"
          body: "Este PR foi criado automaticamente para merge de develop em homolog."
          draft: false  # Cria o PR como "aberto" (não como rascunho)

  create-pr-to-main:
    runs-on: ubuntu-latest
    needs: create-pr-to-homolog  # Só executa após o PR para homolog ser criado
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged && github.event.pull_request.base.ref == 'homolog'

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Git
      - name: Set up Git
        run: |
          git config --global user.name "anndrezoide"
          git config --global user.email "dhegomeez@gmail.com"

      # Passo 3: Criar Pull Request de homolog para main
      - name: Create Pull Request to Main
        id: create-pr-main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # Branch de destino
          head: homolog  # Branch de origem
          title: "PR: Merge homolog into main"
          body: "Este PR foi criado automaticamente para merge de homolog em main."
          draft: false  # Cria o PR como "aberto" (não como rascunho)
