name: CI/CD Pipeline

on:
  push:
    branches:
      - develop  # A pipeline será acionada apenas com push na branch "develop"

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr-and-merge:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Git
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Passo 3: Criar Pull Request de develop para homolog
      - name: Create Pull Request to Homolog
        id: create-pr-homolog
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: homolog  # Branch de destino
          head: develop  # Branch de origem
          title: "PR: Merge develop into homolog"
          body: "Este PR foi criado automaticamente para merge de develop em homolog."
          draft: false  # Cria o PR como "aberto" (não como rascunho)

      # Passo 4: Executar testes (exemplo com Maven)
      - name: Run Tests
        run: |
          mvn clean install
          mvn test

      # Passo 5: Criar Pull Request de homolog para main (após testes bem-sucedidos)
      - name: Create Pull Request to Main
        if: success()  # Só executa se os testes passarem
        id: create-pr-main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # Branch de destino
          head: homolog  # Branch de origem
          title: "PR: Merge homolog into main"
          body: "Este PR foi criado automaticamente para merge de homolog em main."
          draft: false

      # Passo 6: Fazer merge automático do PR de homolog para main
      - name: Merge Pull Request to Main
        if: success()  # Só executa se os testes passarem
        uses: peter-evans/merge-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.create-pr-main.outputs.pull-request-number }}
          merge-method: merge  # Método de merge (merge, squash, rebase)
